############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Welcome to the cState configuration file!
#
# If you are using an earlier version, or one
# in the future, such as v8.0 you may see errors
# pop up when deploying a cState website.
#
# Now, onto the fun part.
#
# Hugo is used for building the status page,
# so this file can be used to change how
# your status page should behave or look.
#
# If you want to use special characters,
# such as accented letters, you MUST save
# the file as UTF-8, not ANSI.
#
# If cState does not load, ensure that:
#  - No tabs are present;
#    YAML only allows spaces
#  - Indents are correct
#    YAML hierarchy is based entirely on indentation
#  - You have "escaped" all apostrophes
#    in your text: If you want to write "don't",
#    for example, write "don''t" instead!
#    Note the doubled apostrophe.
#  - Text with symbols is enclosed in single
#    or double quotation marks.
#
# If you have problems, create an issue on GitHub:
# https://github.com/cstate/cstate/issues

############################################################
# +------------------------------------------------------+ #
# |                  Basic metadata                      | #
# +------------------------------------------------------+ #
############################################################

# What is your status page called?
# Shows up in the browser bar and meta tags
title: Vite Gateways Status

# Should posts, which have a publish date
# from the future, be built? Useful for
# sharing upcoming maintenance, etc.
#
# We recommend to keep this at `true`.
# BOOLEAN; `true`, `false`
buildFuture: false

# What language do you want to use for the
# html[lang] definition?
#
# Does not change language of site
# itself.
#
# Default: `en`
# ISO 639-1 defines abbreviations.
#
# See:  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Also: https://www.w3schools.com/tags/ref_language_codes.asp
languageCode: en

# What translation file should cState use?
# You can also define whether missing
# translations should get placeholders.
#
# For defaultContentLanguage—
# Default: `en`
#
# For enableMissingTranslationPlaceholders—
# do not set it to true for languages other
# than English! When tested with Lithuanian,
# it would add unnecesary placeholders to
# values that were intentionally empty.
defaultContentLanguage: en

# What is the hostname or path to the root?
# Where is the site hosted?
#
# ❗ cState & Hugo don’t support '/' in
# production use. It will break RSS
# feeds and breaks permalinks since
# version 3. If you are just testing,
# localhost should automatically work.
#
# Example: 
# baseUrl: https://status.example.com/
#
# For testing:
# baseUrl: http://localhost
#
# Broken example:
# baseUrl: /
baseURL: https://gateways.onvite.app

# For features like Last modified, you
# need to use a Git repository. If you
# are using Netlify, you are already
# using Git (with GitHub, GitLab, etc)
#
# So, should Git information be used
# for this website?
#
# We recommend to keep this at `true`.
# BOOLEAN; `true`, `false`
enableGitInfo: true

############################################################
# +------------------------------------------------------+ #
# |                   Preferences                        | #
# +------------------------------------------------------+ #
############################################################

params:
  # Before setting up your systems, you need
  # to first define at least one category.
  #
  # Categories are shown in the order that
  # you define in this config file.
  #
  # Categories can have a:
  # - name
  # - description
  # - closed boolean `closed: true`
  #   That would collapse the category upon first load
  #   and the user can expand by clicking on the category
  #   (Requires JavaScript.)
  # - untitled boolean `untitled: true`
  #   This would complerely hide the name of the category.
  #   This is useful, if you do not want to use categories
  #   because you need to set an 'Uncategorized' category.
  #   Or it can be used alongside other categories.
  #
  # These are case sensitive.
  #
  # For help, see the wiki:
  # https://github.com/cstate/cstate/wiki/Customization
  categories:
    - name: ExperimentDAO
      description: The Most Advanced Gateway DAO on VITE. As a gateway, eDAO bridges
        external cryptocurrencies making a real change in the crypto ecosystem.
      closed: true
    - name: GateK
      description: A Gateway DAO on Vite that bridges revolutionary networks.
      closed: true
    - name: VGATE
      description: As an operator of ViteX, VGATE is responsible for listing coins, deposit
        and withdrawal, cryptocurrency marketing and promoting and other
        services within VGATE's own marketing area.VGATE has complete
        capabilities as an operator, namely the capabilities of operating VGATE
        and its cryptos. In addition to helping users list cryptos, deposit and
        withdraw, and adjust transaction fees, VGATE can also mint coins, help
        other operators mint coins and run their gateways.
      closed: true
    - name: ViNo
      description: ViNo Gateway runs cross-chain services for various cryptocurrencies on
        Vitex
      closed: true
    - name: Vite Gateway
      description: "Vite Gateway runs cross-chain services for four coins: BTC, ETH,
        USDT(ERC20)"
      closed: true
    - name: XGate
      description: XGate runs cross-chain services for various cryptocurrencies on Vitex
      closed: true

  # These are your systems. Change them to
  # change the amount of components.
  #
  # These are case sensitive.
  #
  # For help, see the wiki:
  # https://github.com/cstate/cstate/wiki/Customization
  systems:
    - name: Terra (LUNA-002) [TERRA]
      category: ExperimentDAO
    - name: TerraUSD (UST) [TERRA]
      category: ExperimentDAO
    - name: Luna (LUNA-003) [TERRA2]
      category: ExperimentDAO
    - name: Saito (SAITO) [BSC]
      category: ExperimentDAO
    - name: Vitamin Coin (VITC) [BSC]
      category: ExperimentDAO
    - name: Vitamin Coin (VITC) [TERRA]
      category: ExperimentDAO
    - name: Vitamin Coin (VITC) [ONE]
      category: ExperimentDAO
    - name: VITCWONE LP (VITCWONE) [ONE]
      category: ExperimentDAO
    - name: Wax (WAXP) [WAX]
      category: ExperimentDAO
    - name: Fantom (FTM) [FTM]
      category: ExperimentDAO
    - name: Avalanche (AVAX) [AVAX]
      category: ExperimentDAO
    - name: ViCat (VICAT) [BSC]
      category: ExperimentDAO
    - name: Ananos (ANA) [ANA]
      category: ExperimentDAO
    - name: Ananos (ANA) [XLM]
      category: ExperimentDAO
    - name: Manangos (MANGO) [XLM]
      category: ExperimentDAO
    - name: VITCWBNB LP (VITCWBNB) [BSC]
      category: ExperimentDAO
    - name: ViCatBNB LP (VICATBNB) [BSC]
      category: ExperimentDAO
    - name: Autentk (AUTK) [BSC]
      category: ExperimentDAO
    - name: VITCWUST LP (VITCWUST) [TERRA]
      category: ExperimentDAO
    - name: Render Token (RNDR) [ETH]
      category: ExperimentDAO
    - name: Hummingbot (HBOT) [ETH]
      category: ExperimentDAO
    - name: Bend DAO (BEND) [ETH]
      category: ExperimentDAO
    - name: Shiba Inu (SHIB) [ETH]
      category: ExperimentDAO
    - name: VIVA (VIVA) [BSC]
      category: ExperimentDAO
    - name: VIVABNB LP (VIVABNB) [BSC]
      category: ExperimentDAO
    - name: Dogecoin (DOGE-001) [DOGE]
      category: ExperimentDAO
    - name: Canto (CANTO) [CANTO]
      category: ExperimentDAO
    - name: Kaspa (KAS) [Kaspa]
      category: GateK
    - name: Hedera (HBAR) [Hedera]
      category: GateK
    - name: TERA (TERA) [TERA]
      category: VGATE
    - name: Bismuth (BIS) [BIS]
      category: VGATE
    - name: DERO (DERO) [DERO]
      category: VGATE
    - name: TurtleCoin (TRTL) [TURTLE]
      category: VGATE
    - name: Ergo (ERG) [ERGO]
      category: VGATE
    - name: Beam (BEAM) [BEAM]
      category: VGATE
    - name: Dune (DUN) [DUNE]
      category: VGATE
    - name: PegNet (PEG) [PEGNET]
      category: VGATE
    - name: pFCT_PegNet (PFCT-001) [PEGNET]
      category: VGATE
    - name: pUSD_PegNet (PUSD) [PEGNET]
      category: VGATE
    - name: pGOLD_PegNet (PGOLD-001) [PEGNET]
      category: VGATE
    - name: Litecash (CASH) [LITECASH]
      category: VGATE
    - name: Bitgrin (XBG) [XBG]
      category: VGATE
    - name: Banano (BAN) [BAN]
      category: VGATE
    - name: IxiCash (IXI) [IXI]
      category: VGATE
    - name: Defis (XGM) [DEFIS]
      category: VGATE
    - name: MoneroV (XMV) [XMV]
      category: VGATE
    - name: Robonomics Network (XRT) [ETH]
      category: VGATE
    - name: FLAMA (FMA) [ETH]
      category: VGATE
    - name: SparkPoint (SRK) [ETH]
      category: VGATE
    - name: Hathor (HTR) [HTR]
      category: VGATE
    - name: Epic Cash (EPIC-002) [EPIC]
      category: VGATE
    - name: DNAxCAT (DXCT) [BSC]
      category: VGATE
    - name: Nano (NANO-001) [NANO]
      category: ViNo
    - name: Banano (BAN-001) [BAN]
      category: ViNo
    - name: Ethereum (ETH) [ETH]
      category: Vite Gateway
    - name: Bitcoin (BTC) [BTC]
      category: Vite Gateway
    - name: Tether USD (USDT) [ETH]
      category: Vite Gateway
    - name: Grin (GRIN) [GRIN]
      category: Vite Gateway
    - name: Ankr (ANKR) [ETH]
      category: Vite Gateway
    - name: Binance USD (BUSD) [ETH]
      category: Vite Gateway
    - name: Binance USD (BUSD) [BSC]
      category: Vite Gateway
    - name: Ripple (XRP-001) [XRP]
      category: Vite Gateway
    - name: EOS (EOS-003) [EOS]
      category: Vite Gateway
    - name: Waves (WAVES) [WAVES]
      category: Vite Gateway
    - name: Tellor (TRB) [ETH]
      category: Vite Gateway
    - name: OKB (OKB-001) [ETH]
      category: Vite Gateway
    - name: Ferrum Network (FRM-001) [ETH]
      category: Vite Gateway
    - name: Harmony (ONE-001) [ONE]
      category: Vite Gateway
    - name: Harmony (ONE-001) [BSC]
      category: Vite Gateway
    - name: Bitcoin Cash (BCH-001) [BCH]
      category: Vite Gateway
    - name: Bitcoin SV (BSV) [BSV]
      category: Vite Gateway
    - name: Chainlink (LINK-001) [ETH]
      category: Vite Gateway
    - name: Monero (XMR) [XMR]
      category: Vite Gateway
    - name: KardiaChain (KAI) [ETH]
      category: Vite Gateway
    - name: Handshake (HNS) [HNS]
      category: Vite Gateway
    - name: Nami Corporation Token (NAMI) [ETH]
      category: Vite Gateway
    - name: Auto (AUTO) [BSC]
      category: Vite Gateway
    - name: HecoFi (HFI) [HECO]
      category: Vite Gateway
    - name: VITE (VITE) [ETH]
      category: Vite Gateway
    - name: VITE (VITE) [BSC]
      category: Vite Gateway
    - name: ViteX Coin (VX) [BSC]
      category: Vite Gateway
    - name: Non Fungible Yearn (NFY) [ETH]
      category: Vite Gateway
    - name: Radicle (RAD) [ETH]
      category: Vite Gateway
    - name: Alchemist (MIST) [ETH]
      category: Vite Gateway
    - name: WaultSwap (WEX) [BSC]
      category: Vite Gateway
    - name: PantherSwap (PANTHER) [BSC]
      category: Vite Gateway
    - name: Binance Coin (BNB-001) [BSC]
      category: Vite Gateway
    - name: PAW (PAW) [PAW]
      category: XGate
    - name: PancakeSwap (CAKE) [BSC]
      category: XGate
    - name: Volt Inu (VOLT) [BSC]
      category: XGate
    - name: Uniswap (UNI) [ETH]
      category: XGate
    - name: Polygon (MATIC) [BSC]
      category: XGate
    - name: Polygon (MATIC) [MATIC]
      category: XGate
    - name: PooCoin (POOCOIN) [BSC]
      category: XGate
    - name: Minato (MNTO) [BSC]
      category: XGate
    - name: Gnosis (GNO) [Gnosis]
      category: XGate
    - name: Celo (CELO) [Celo]
      category: XGate
    - name: TRON (TRX) [TRX]
      category: XGate
    - name: Stellar (XLM) [XLM]
      category: XGate
    - name: VINUBNB PCS (VINUBNB) [BSC]
      category: XGate
    - name: VITA INU (VINU-001) [ETH]
      category: XGate
    - name: VITA INU (VINU-001) [BSC]
      category: XGate
    - name: VITA INU (VINU-001) [MATIC]
      category: XGate

  # What date format to use?
  #
  # Hugo formatting docs:
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  #
  # Technical: GOLANG/HUGO .Date.Format & dateFormat
  #
  # dateFormat Default: "January 2, 2006 at 3:04 PM"
  # shortDateFormat Default: "15:04 — Jan 2"
  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2

  # Should relative time (x min ago) be used?
  #
  # IMPORTANT: In the frontmatter, the dates MUST be in
  # the UTC time zone for this to work preperly. If you 
  # use Netlify CMS, all good — the CMS picks UTC time
  # by default. Otherwise, there may be very inaccurate
  # times if multiple time zones are in your issue files.
  #
  # FOR YOUR CONSIDERATION: This feature was introduced in
  # v5. It may be a breaking change in the case when you
  # wish to use relative time but old issues do not have
  # UTC time (and therefore are out of sync by ±24 hours)
  #
  # Read the wiki for more: 
  # https://github.com/cstate/cstate/wiki/Customization#time 
  #
  # If enabled, will display relative times in places like
  # the incident history and summaries instead of using
  # dateFormat and shortDateFormat (except for if you use
  # the old shortcode).
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  useRelativeTime: true

  # If enabled, doesn't show seconds on relative times.
  #
  # With option ON (true):
  # "Last checked <1 min ago"
  #
  # With option OFF (false; default):
  # "Last checked 20s ago"
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  skipSeconds: false

  # Should there be an automatic "Last updated"
  # text shown below issues?
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  enableLastMod: true

  # What header design should we use?
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  useLargeHeaderDesign: false

  # Should incident history be separated
  # like in an archive view?
  #
  # Note: This WILL disable pagination.
  #
  # Default: `yearly`
  # STRING; `monthly`, `yearly`, `none`
  incidentHistoryFormat: "yearly"

  # Should incident history be hidden?
  #
  # By disabling the incident history, you also disable
  # the RSS feed. To ensure no incidents are shown, you
  # should delete them after they are resolved. This option
  # overrides any other options that tailor your incident
  # history’s look.
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  disableIncidentHistory: false

  # Disable dark mode
  #
  # If your OS and browser support the
  # `prefers-color-scheme` media query,
  # cState will automatically switch to
  # a darker user interface.
  #
  # cState uses its built-in colors for
  # most of the interface to ensure
  # a good user experience.
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  disableDarkMode: false

  # Should we show the logo or the title
  # of the status page?
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  useLogo: false

  # Where is the logo located, if one is
  # present at all?
  #
  # Recommended: png is best used for
  # images like logos.
  #
  # Recommended: png, bmp, jpg, or gif
  # for best browser support!
  logo: logo.png

  # This is the description that is shown
  # on the footer and meta tags.
  #
  # Default: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.
  description: This webpage continuously monitor all gateways on vite.

  # Tabs on homepage
  # Uncomment to enable.
  #
  # Format:
  # customTabs:
  #  -
  #    name: Name
  #    link: https://example.com

  # Disable complex server-side
  # calculations that may impact
  # your build performance
  #
  # Disables math calculations
  # for average downtime on
  # systems ("/affected/") pages
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  disableComplexCalculations: false

  # Incident posts shown
  # in one page
  #
  # NUMERIC; Default: `10`
  incidentPostsPerPage: 10

  # Colors throughout cState
  #
  # We recommend using HEX
  # (with the # symbol).
  #
  # Defaults:
  #
  # brand: "#0a0c0f"
  # ok: "#008000"
  # disrupted: "#cc4400"
  # down: "#e60000"
  # notice: "#24478f"
  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"

  # If the status page shows that
  # there are disruptions or outages
  # happening, should it keep the
  # brand header color or drop it
  # and use the status indication
  # colors that were just defined?
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  alwaysKeepBrandColor: true

  # Introduced in v4.0.1 for consistent
  # site title text color.
  #
  # If you do not use the logo, what color
  # should the site text color be?
  #
  # Removing this option will not force
  # any site text color. This is likely
  # unwanted behavior.
  #
  # Default: `white`
  # STRING; `white`, `black`, or nothing
  headerTextColor: white

  # Google Analytics tracking code
  #
  # By default, cState does not use
  # Google Analytics. If you choose
  # to use it, you may change the
  # placeholder code below to your
  # own and thereby enable the
  # tracking service.
  #
  # To disable the analytics, change
  # the value to the default:
  #
  # Default: UA-00000000-1
  googleAnalytics: UA-00000000-1

# These options affect the core of cState.
# Please do not change them if you do not
# know what you are doing.
theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
